from django.urls import path, include
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required, user_passes_test


urlpatterns = [
     path('', views.home, name='home'),
     path('langs', views.LangsList.as_view(), name='langs_list'),
     path('langs/create', views.LngCreateView.as_view(), name='create_lang'),
     path('langs/<int:pk>/edit', views.LangsUpdate.as_view(), name='lang_update'),
     path('langs/delete', views.delete_langs, name='lang_del'),
     path("site_infos", views.StaticUpdate.as_view(), name='static_info'),
     path('images/save', views.save_images, name='images_save'),
     path("images/delete", views.delete_image, name='del-img'),
     path('translations', views.TranslationList.as_view(), name='translation_list'),
     path("translations/<int:pk>", views.TranslationGroupDetail.as_view(), name='transl_group_detail'),
     path('translation/edit', views.translation_update, name='translation_edit'),
     path("translations/<int:pk>/edit", views.TranslationGroupUdpate.as_view(), name='transl_group_edit'),
     path("translation_group/create", views.add_trans_group, name='transl_group_create'),
     path("delete", views.delete_item, name='delete'),
     path("lang_icon_delete", views.del_lang_icon, name='lang_icon_del'),
     path("add_static_image", views.add_static_image, name='add_static_logos'),
     path("delete_static_image", views.del_statics_image, name='del_static_image'),
     path('delete_article_ctg_images', views.delete_article_group_img, name='art_ctg_image_del'),
     path('login', LoginView.as_view(
          template_name='admin/sing-in.html',
          success_url='/admin/',
     ), name='login_admin'),
     path('logout', views.logout_view, name='logout_url'),
     path('admins', views.AdminsList.as_view(), name='admin_list'),
     path("admins/create", views.AdminCreate.as_view(), name='admins_create'),
     path("admins/<int:pk>/edit", views.AdminUpdate.as_view(), name='admins_edit'),
     path("delete_article_image", views.delete_article_image, name='del_article_img'),
     path('quick_applications', views.ShortApplicationList.as_view(), name='short_aplic_list'),
     path('quick_applications/<int:pk>/edit', views.ShortApplicationUpdate.as_view(), name='short_aplic_edit'),
     path('categories', views.CategoryList.as_view(), name='category_list'),
     path('categories/create', views.CategoryCreate.as_view(), name='category_create'),
     path("categories/<int:pk>/edit", views.CategoryEdit.as_view(), name='category_edit'),
     path('del_ctg_files', views.del_category_file, name='del_ctg_file'),
     path("products", views.ProductsList.as_view(), name='products_list'),
     path('products/create', views.ProductCreateView.as_view(), name='products_create'),
     path("faq", views.FAQlist.as_view(), name='faq_list'),
     path("faq/create", views.FAQcreate.as_view(), name='faq_create'),
     path("faq/<int:pk>/edit", views.FAQupdate.as_view(), name='faq_edit'),
     path("delete_products_image", views.del_product_image, name='del_prod_img'),
     path('atributs', views.AtributsList.as_view(), name='atr_list'),
     path("atributs/create", views.AtributsCreate.as_view(), name='atr_create'),
     path("atributs/<int:pk>/edit", views.AtributEdit.as_view(), name='atribut_edit'),
     path("atribut_options/edit", views.AtributOptionEdit.as_view(), name='atr_options_edit'),
     path("atribut_options/get", views.get_option, name='get_atr_option'),
     path('colors', views.ColorsList.as_view(), name='color_list'),
     path("colors/create", views.ColorsCreate.as_view(), name='color_create'),
     path("colors/<int:pk>/edit", views.ColorEdit.as_view(), name='colors_edit'),
     path("atributs/<int:pk>", views.AtributsDetailView.as_view(), name='atribut_detail'),
     path('baners', views.BanersList.as_view(), name='baners_list'),
     path('baners/create', views.BanerCreate.as_view(), name='baner_create'),
     path('baners/<int:pk>/edit', views.BanerEdit.as_view(), name='baner_edit'),
     path("delete_baner_img", views.delete_baner_img, name='del_baner_img'),
     path("get_post_ctg", views.get_post_ctg, name='get_post_category'),
     path("get_atributs", views.get_atributs, name='get_atributs'),
     path("product/create/post", views.create_product, name='create_product'),
    path('products/<int:pk>/edit', views.ProductEditView.as_view(), name='products_edit'),
     path('products/<int:pk>/edit/post', views.edit_product, name='edit_product'),
     path('designs', views.DesignsList.as_view(), name='designs_list'),
     path('designs/create', views.CustomDesignCreate.as_view(), name='design_crate'),
     path('designs/<int:pk>/edit', views.CustomDesignEdit.as_view(), name='design_edit')
]
