# Generated by Django 4.1 on 2023-02-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
