# Generated by Django 4.1 on 2023-02-21 10:58

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_faq_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategories',
            name='name',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='staticinformation',
            name='title',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Заголовок сайта'),
        ),
    ]
