# Generated by Django 4.1 on 2023-02-21 13:34

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_articlecategories_name_alter_articles_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticinformation',
            name='title',
            field=models.JSONField(blank=True, null=True, validators=[admins.models.json_field_validate], verbose_name='Заголовок сайта'),
        ),
    ]
