# Generated by Django 4.1 on 2023-02-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_staticinformation_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partners',
        ),
    ]
