# Generated by Django 4.1 on 2023-02-25 12:51

import admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributoptions',
            name='name',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='atributs',
            name='name',
            field=models.JSONField(validators=[admins.models.json_field_validate], verbose_name='name'),
        ),
    ]
