# Generated by Django 4.1 on 2023-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_colors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='bb_date',
        ),
    ]
