# Generated by Django 4.1 on 2023-02-26 17:51

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_products_bb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducVariantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='variant_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='image',
        ),
        migrations.AddField(
            model_name='productvariants',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='main.producvariantimages'),
        ),
    ]
