# Generated by Django 4.1 on 2023-02-28 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_producvariantimages_remove_productvariants_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='contract_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
    ]
