# Generated by Django 4.1 on 2023-03-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productvariants_contract_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
