# Generated by Django 4.1 on 2023-03-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='baners',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
