# Generated by Django 4.1 on 2023-03-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_newsletter_number_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baners',
            name='baner',
            field=models.JSONField(blank=True, null=True, verbose_name='Baner'),
        ),
    ]
