# Generated by Django 4.1 on 2023-03-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_baners_baner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariants',
            name='code',
        ),
    ]
