# Generated by Django 4.1 on 2023-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_customdesigns_alter_baners_baner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdesigns',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
