# Generated by Django 4.1 on 2023-03-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_customdesigns_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdesigns',
            name='order',
        ),
        migrations.AddField(
            model_name='baners',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='order'),
        ),
    ]
