# Generated by Django 4.1 on 2023-02-26 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_producvariantimages_remove_productvariants_image_and_more'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('nbm', models.CharField(max_length=255, verbose_name='Nbm')),
                ('total_price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
            ],
        ),
        migrations.RemoveField(
            model_name='shortapplication',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='shortapplication',
            name='product',
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Count')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productvariants')),
            ],
        ),
    ]
