# Generated by Django 4.1 on 2023-02-27 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_remove_shortapplication_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Рассмотрено', 'Рассмотрено'), ('Отклонено', 'Отклонено')], default='На рассмотрении', max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price'),
        ),
    ]
